language: android

android:
  components:
    - build-tools-19.1.0

env:
  global:
    - TERM=dumb
  matrix:
    - ANDROID_SDKS=android-19,sysimg-19  ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

before_install:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

before_script:
  - adb wait-for-device
  - adb shell input keyevent 82 &

notifications:
  email: false
